name: metrics_guidance_retrosynthesis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.1
  - rdkit=2023.03.3
  - networkx=3.2.1
  - matplotlib=3.8.3
  - pycairo=1.23.0
  - python-graphviz=0.20.1
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - joblib=1.3.2
  - jupyter=1.0.0
  - tqdm=4.66.2
  - pyyaml=6.0.1
  - yaml=0.2.5
  - requests=2.31.0
  - pip=24.0
  - pip:
      - fastapi==0.111.0
      - pydantic==1.10.12
      - rdchiral>=1.1.0 
      - rxnmapper>=0.4.0
      - transformers>=4.0.0
      - pymongo==4.6.2
      - python-json-logger==2.0.7
      - pebble==5.0.6
      - urllib3>=1.26.0
      
